networks:
    ispa:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "172.18.0.0/16"

services:  
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    hostname: spark-master
    user: root
    volumes:
      - ./spark/logs:/opt/bitnami/spark/logs
      - ./spark/apps:/opt/bitnami/spark/apps
    ports:
      - '8080:8080'
      - '7077:7077'
    networks:
      ispa:
        ipv4_address: 172.18.0.2

  spark-worker:
    image: bitnami/spark:latest
    container_name: spark-worker
    hostname: spark-worker
    user: root
    ports:
      - '8085:8081'
    depends_on:
      - spark-master
    environment:
      - MASTER_URL=spark://172.18.0.2:7077
      - SPARK_MODE=worker
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
    volumes:
      - ./spark/logs:/opt/bitnami/spark/logs
    networks:
      ispa:
        ipv4_address: 172.18.0.3


    
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      ispa:
        ipv4_address: 172.18.0.4

  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    hostname: kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://172.18.0.5:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://172.18.0.5:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - ./kafka/logs:/bitnami/kafka/logs
    depends_on:
      - zookeeper
    networks:
      ispa:
        ipv4_address: 172.18.0.5


  scraping_app:
    image: 'python:latest'
    container_name: app
    hostname: app
    ports:
      - '5000:5000'
    depends_on:
      - kafka
      - spark-master
    volumes:
      - ./extracting_app:/app
      - ./requirements.txt:/app/requirements.txt
    entrypoint: tail -f /dev/null
    command: ["python3", "/app/app.py"]
    networks:
      ispa:
        ipv4_address: 172.18.0.6