networks:
    ispa:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "172.18.0.0/16"

services:  
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    hostname: spark-master
    user: root
    volumes:
      - ./spark/checkpoint:/tmp/checkpoint
      - ./spark/utils:/opt/bitnami/spark/utils
    ports:
      - '8080:8080'
      - '7077:7077'
    networks:
      ispa:
        ipv4_address: 172.18.0.2

  spark-worker1:
    image: bitnami/spark:latest
    container_name: spark-worker1
    hostname: spark-worker1
    user: root
    ports:
      - '8081:8081'
    depends_on:
      - spark-master
    environment:
      - MASTER_URL=spark://172.18.0.2:7077
      - SPARK_MODE=worker
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
    networks:
      ispa:
        ipv4_address: 172.18.0.3

  spark-worker2:
    image: bitnami/spark:latest
    container_name: spark-worker2
    hostname: spark-worker2
    user: root
    ports:
      - '8082:8081'
    depends_on:
      - spark-master
    environment:
      - MASTER_URL=spark://172.18.0.2:7077
      - SPARK_MODE=worker
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
    networks:
      ispa:
        ipv4_address: 172.18.0.4

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      ispa:
        ipv4_address: 172.18.0.5

  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    hostname: kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://172.18.0.6:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://172.18.0.6:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - ./kafka/data:/bitnami/kafka/data
    depends_on:
      - zookeeper
    networks:
      ispa:
        ipv4_address: 172.18.0.6

  scraping_app:
    image: 'python:latest'
    container_name: app
    hostname: app
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - REDDIT_USERNAME=${REDDIT_USERNAME}
      - REDDIT_PASSWORD=${REDDIT_PASSWORD}
    depends_on:
      - kafka
    volumes:
      - ./data scraping:/app/
    entrypoint: "/bin/bash /app/scripts/entrypoint.sh"
    networks:
      ispa:
        ipv4_address: 172.18.0.7

  cassandra:
    image: bitnami/cassandra:latest
    container_name: cassandra
    hostname: cassandra
    environment:
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD=cassandra
    ports:
      - 9042:9042
    networks:
      ispa:
        ipv4_address: 172.18.0.8

  model-endpoint:
    image: 'python:latest'
    container_name: model-endpoint
    hostname: model-endpoint
    volumes:
      - ./model_endpoint:/model_endpoint/
    ports:
      - '5000:5000'
    entrypoint: "/bin/bash /model_endpoint/scripts/entrypoint.sh"
    networks:
      ispa:
        ipv4_address: 172.18.0.9