credentials_file = "../credentials/credentials.json"
project_id       = "foot-analysis-422908"
region           = "us-central1"
bucket_name      = "spark-bucket"
dataset_id       = "ipc_dataset"
table_id         = "comments_count"