subreddits:
  - "worldnews"
  - "IsraelPalestine"
  - "geopolitics"
  - "conspiracy"
  - "news"
  - "politics"
  - "AskMiddleEast"
  - "Ask_Politics"
  - "Palestine"
  - "IsraelPalestineWar_23"